### ISSUE TITLE
Integrate this with retakes

### ISSUE THREAD

**Issue by everkk** [audiomaster99/CS2BombsiteAnnouncer#4] opened 2024-03-24 13:19 UTC
Can integrate this with https://github.com/B3none/cs2-retakes?

**Comment by itsAudioo** [comment] 2024-03-26 05:19
as soon as Im able I will try and make it work for retake

**Comment by freakexeuLow** [comment] 2024-03-27 03:49
> Can integrate this with https://github.com/B3none/cs2-retakes?

so i even use it for retake and it works without any problems...or am i misunderstanding something here?

**Comment by everkk** [comment] 2024-03-27 11:08
> > Can integrate this with https://github.com/B3none/cs2-retakes?
> 
> so i even use it for retake and it works without any problems...or am i misunderstanding something here?

On my server is working ugly, on dd2 shows always b when is a. On overpass same case. It's the same on many other maps.

**Comment by Micka2302** [comment] 2024-04-03 15:50
> > > Can integrate this with https://github.com/B3none/cs2-retakes?
> > 
> > 
> > so i even use it for retake and it works without any problems...or am i misunderstanding something here?
> 
> On my server is working ugly, on dd2 shows always b when is a. On overpass same case. It's the same on many other maps.

Confirmed, me too i got this bug.

**Comment by itsAudioo** [comment] 2024-04-07 15:45
@MickaNoob @everkk @freakexeuLow 
https://github.com/audiomaster99/CS2BombsiteAnnouncer/releases/tag/build-21
Try latest build

**Comment by Micka2302** [comment] 2024-04-08 16:20
Fixed. 

Thanks for fix.

**Comment by itsAudioo** [comment] 2024-04-08 18:17
I will close this issue since a few people have confirmed that its been fixed.

**Closed as completed by itsAudioo** 2024-04-08 18:17 UTC
